export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

type MaterialCategory = "placas" | "herrajes" | "perfiles" | "insumos" | "logistica" | "servicios";
type MaterialUnit = "unidad" | "m2" | "m" | "kg" | "hora";
type JobStatus =
  | "por_cotizar"
  | "presupuestado"
  | "aprobado"
  | "en_produccion"
  | "instalado"
  | "entregado"
  | "cobrado";

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          full_name: string;
          email: string | null;
          phone: string | null;
          avatar_url: string | null;
          locale: string;
          timezone: string;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
          deleted_at: string | null;
          deleted_by: string | null;
        };
        Insert: {
          id?: string;
          full_name: string;
          email?: string | null;
          phone?: string | null;
          avatar_url?: string | null;
          locale?: string;
          timezone?: string;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_at?: string | null;
          deleted_by?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["profiles"]["Insert"]>;
      };
      settings: {
        Row: {
          id: string;
          profile_id: string | null;
          horas_productivas_mes: number;
          costos_fijos_mes: number;
          costo_hora_taller: number;
          desperdicio_melamina_pct: number;
          margen_medida_pct: number;
          margen_ecommerce_pct: number;
          impuestos_pct: number;
          publicidad_pct: number;
          comision_cobro_pct: number;
          embalaje_promedio: number;
          envio_promedio: number;
          kerf_sierra_mm: number;
          margen_perimetral_placa_mm: number;
          permitir_rotacion_por_defecto: boolean;
          veta_obligatoria_por_defecto: boolean;
          is_active: boolean;
          notes: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
          deleted_at: string | null;
          deleted_by: string | null;
        };
        Insert: {
          id?: string;
          profile_id?: string | null;
          horas_productivas_mes?: number;
          costos_fijos_mes?: number;
          costo_hora_taller?: number;
          desperdicio_melamina_pct?: number;
          margen_medida_pct?: number;
          margen_ecommerce_pct?: number;
          impuestos_pct?: number;
          publicidad_pct?: number;
          comision_cobro_pct?: number;
          embalaje_promedio?: number;
          envio_promedio?: number;
          kerf_sierra_mm?: number;
          margen_perimetral_placa_mm?: number;
          permitir_rotacion_por_defecto?: boolean;
          veta_obligatoria_por_defecto?: boolean;
          is_active?: boolean;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_at?: string | null;
          deleted_by?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["settings"]["Insert"]>;
      };
      clients: {
        Row: {
          id: string;
          profile_id: string | null;
          nombre: string;
          telefono: string | null;
          email: string | null;
          direccion: string | null;
          ciudad: string | null;
          provincia: string | null;
          notas: string | null;
          canal_ingreso: string | null;
          fecha_alta: string | null;
          saldo_pendiente: number;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
          deleted_at: string | null;
          deleted_by: string | null;
        };
        Insert: {
          id?: string;
          profile_id?: string | null;
          nombre: string;
          telefono?: string | null;
          email?: string | null;
          direccion?: string | null;
          ciudad?: string | null;
          provincia?: string | null;
          notas?: string | null;
          canal_ingreso?: string | null;
          fecha_alta?: string | null;
          saldo_pendiente?: number;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_at?: string | null;
          deleted_by?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["clients"]["Insert"]>;
      };
      suppliers: {
        Row: {
          id: string;
          profile_id: string | null;
          nombre: string;
          telefono: string | null;
          email: string | null;
          ciudad: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
          deleted_at: string | null;
          deleted_by: string | null;
        };
        Insert: {
          id?: string;
          profile_id?: string | null;
          nombre: string;
          telefono?: string | null;
          email?: string | null;
          ciudad?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_at?: string | null;
          deleted_by?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["suppliers"]["Insert"]>;
      };
      materials: {
        Row: {
          id: string;
          profile_id: string | null;
          codigo: string;
          nombre: string;
          categoria: MaterialCategory | string;
          unidad: MaterialUnit | string;
          costo_unitario: number;
          supplier_id: string | null;
          marca: string | null;
          espesor_mm: number | null;
          largo_mm: number | null;
          ancho_mm: number | null;
          area_m2: number;
          tiene_veta: boolean;
          activo: boolean;
          favorito: boolean;
          observaciones: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
          deleted_at: string | null;
          deleted_by: string | null;
        };
        Insert: {
          id?: string;
          profile_id?: string | null;
          codigo: string;
          nombre: string;
          categoria: MaterialCategory | string;
          unidad: MaterialUnit | string;
          costo_unitario?: number;
          supplier_id?: string | null;
          marca?: string | null;
          espesor_mm?: number | null;
          largo_mm?: number | null;
          ancho_mm?: number | null;
          area_m2?: number;
          tiene_veta?: boolean;
          activo?: boolean;
          favorito?: boolean;
          observaciones?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_at?: string | null;
          deleted_by?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["materials"]["Insert"]>;
      };
      material_price_history: {
        Row: {
          id: string;
          profile_id: string;
          material_id: string;
          price_old: number;
          price_new: number;
          change_reason: string | null;
          effective_from: string;
          effective_to: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          profile_id: string;
          material_id: string;
          price_old: number;
          price_new: number;
          change_reason?: string | null;
          effective_from?: string;
          effective_to?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["material_price_history"]["Insert"]>;
      };
      custom_projects: {
        Row: {
          id: string;
          profile_id: string;
          client_id: string | null;
          nombre_proyecto: string;
          fecha: string;
          tipo_mueble: string | null;
          ancho: number | null;
          alto: number | null;
          profundidad: number | null;
          cantidad: number;
          descuento_pct: number;
          subtotal_materiales: number;
          horas_totales: number;
          costo_mano_obra: number;
          costo_directo: number;
          costo_total: number;
          precio_sugerido: number;
          utilidad_estimada: number;
          status: string;
          settings_snapshot: Json;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
          deleted_at: string | null;
          deleted_by: string | null;
        };
        Insert: {
          id?: string;
          profile_id: string;
          client_id?: string | null;
          nombre_proyecto: string;
          fecha?: string;
          tipo_mueble?: string | null;
          ancho?: number | null;
          alto?: number | null;
          profundidad?: number | null;
          cantidad?: number;
          descuento_pct?: number;
          subtotal_materiales?: number;
          horas_totales?: number;
          costo_mano_obra?: number;
          costo_directo?: number;
          costo_total?: number;
          precio_sugerido?: number;
          utilidad_estimada?: number;
          status?: string;
          settings_snapshot?: Json;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_at?: string | null;
          deleted_by?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["custom_projects"]["Insert"]>;
      };
      custom_project_materials: {
        Row: {
          id: string;
          profile_id: string;
          custom_project_id: string;
          material_id: string | null;
          material_codigo_snapshot: string | null;
          material_nombre_snapshot: string;
          unidad_snapshot: string | null;
          espesor_mm_snapshot: number | null;
          consumo: number;
          desperdicio_pct: number;
          costo_unitario_snapshot: number;
          subtotal_snapshot: number;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
          deleted_at: string | null;
          deleted_by: string | null;
        };
        Insert: {
          id?: string;
          profile_id: string;
          custom_project_id: string;
          material_id?: string | null;
          material_codigo_snapshot?: string | null;
          material_nombre_snapshot: string;
          unidad_snapshot?: string | null;
          espesor_mm_snapshot?: number | null;
          consumo: number;
          desperdicio_pct?: number;
          costo_unitario_snapshot: number;
          subtotal_snapshot: number;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_at?: string | null;
          deleted_by?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["custom_project_materials"]["Insert"]>;
      };
      custom_project_labor: {
        Row: {
          id: string;
          profile_id: string;
          custom_project_id: string;
          proceso_key: string;
          proceso_nombre: string;
          horas: number;
          costo_hora_snapshot: number;
          subtotal_snapshot: number;
          line_order: number;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          profile_id: string;
          custom_project_id: string;
          proceso_key: string;
          proceso_nombre: string;
          horas: number;
          costo_hora_snapshot: number;
          subtotal_snapshot: number;
          line_order?: number;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["custom_project_labor"]["Insert"]>;
      };
      ecommerce_products: {
        Row: {
          id: string;
          profile_id: string | null;
          sku: string;
          nombre: string;
          categoria: string | null;
          precio_mercado: number;
          ancho: number | null;
          alto: number | null;
          profundidad: number | null;
          unidades_lote: number;
          horas_proceso_unit: number;
          embalaje_unitario: number;
          envio_unitario: number;
          costo_materiales_unit: number;
          costo_mano_obra_unit: number;
          costo_base_unit: number;
          costo_con_embalaje: number;
          costo_total_canal: number;
          precio_sugerido: number;
          ganancia_unit: number;
          status: string;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
          deleted_at: string | null;
          deleted_by: string | null;
        };
        Insert: {
          id?: string;
          profile_id?: string | null;
          sku: string;
          nombre: string;
          categoria?: string | null;
          precio_mercado?: number;
          ancho?: number | null;
          alto?: number | null;
          profundidad?: number | null;
          unidades_lote?: number;
          horas_proceso_unit?: number;
          embalaje_unitario?: number;
          envio_unitario?: number;
          costo_materiales_unit?: number;
          costo_mano_obra_unit?: number;
          costo_base_unit?: number;
          costo_con_embalaje?: number;
          costo_total_canal?: number;
          precio_sugerido?: number;
          ganancia_unit?: number;
          status?: string;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_at?: string | null;
          deleted_by?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["ecommerce_products"]["Insert"]>;
      };
      ecommerce_product_materials: {
        Row: {
          id: string;
          profile_id: string;
          ecommerce_product_id: string;
          material_id: string | null;
          material_codigo_snapshot: string | null;
          material_nombre_snapshot: string;
          unidad_snapshot: string | null;
          consumo_unit: number;
          costo_unitario_snapshot: number;
          subtotal_snapshot: number;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          profile_id: string;
          ecommerce_product_id: string;
          material_id?: string | null;
          material_codigo_snapshot?: string | null;
          material_nombre_snapshot: string;
          unidad_snapshot?: string | null;
          consumo_unit: number;
          costo_unitario_snapshot: number;
          subtotal_snapshot: number;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["ecommerce_product_materials"]["Insert"]>;
      };
      ecommerce_product_processes: {
        Row: {
          id: string;
          profile_id: string;
          ecommerce_product_id: string;
          proceso_key: string;
          proceso_nombre: string;
          horas_unit: number;
          costo_hora_snapshot: number;
          subtotal_snapshot: number;
          line_order: number;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          profile_id: string;
          ecommerce_product_id: string;
          proceso_key: string;
          proceso_nombre: string;
          horas_unit?: number;
          costo_hora_snapshot?: number;
          subtotal_snapshot?: number;
          line_order?: number;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["ecommerce_product_processes"]["Insert"]>;
      };
      cut_jobs: {
        Row: {
          id: string;
          profile_id: string | null;
          nombre: string;
          largo_placa_mm: number;
          ancho_placa_mm: number;
          kerf_mm: number;
          margen_perimetral_mm: number;
          desperdicio_extra_pct: number;
          allow_rotation_default: boolean;
          grain_required_default: boolean;
          iteration_actual: number;
          placas_necesarias_snapshot: number;
          aprovechamiento_pct_snapshot: number;
          desperdicio_pct_snapshot: number;
          costo_placas_snapshot: number;
          status: string;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
          deleted_at: string | null;
          deleted_by: string | null;
        };
        Insert: {
          id?: string;
          profile_id?: string | null;
          nombre: string;
          largo_placa_mm?: number;
          ancho_placa_mm?: number;
          kerf_mm?: number;
          margen_perimetral_mm?: number;
          desperdicio_extra_pct?: number;
          allow_rotation_default?: boolean;
          grain_required_default?: boolean;
          iteration_actual?: number;
          placas_necesarias_snapshot?: number;
          aprovechamiento_pct_snapshot?: number;
          desperdicio_pct_snapshot?: number;
          costo_placas_snapshot?: number;
          status?: string;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_at?: string | null;
          deleted_by?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["cut_jobs"]["Insert"]>;
      };
      cut_job_parts: {
        Row: {
          id: string;
          profile_id: string;
          cut_job_id: string;
          pieza: string;
          cantidad: number;
          largo_mm: number;
          ancho_mm: number;
          material_id: string | null;
          espesor_mm: number | null;
          rotacion_permitida: boolean;
          veta_obligatoria: boolean;
          canto: string | null;
          prioridad: number;
          observacion: string | null;
          bloqueada: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
          deleted_at: string | null;
          deleted_by: string | null;
        };
        Insert: {
          id?: string;
          profile_id: string;
          cut_job_id: string;
          pieza: string;
          cantidad: number;
          largo_mm: number;
          ancho_mm: number;
          material_id?: string | null;
          espesor_mm?: number | null;
          rotacion_permitida?: boolean;
          veta_obligatoria?: boolean;
          canto?: string | null;
          prioridad?: number;
          observacion?: string | null;
          bloqueada?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_at?: string | null;
          deleted_by?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["cut_job_parts"]["Insert"]>;
      };
      cut_job_layouts: {
        Row: {
          id: string;
          profile_id: string;
          cut_job_id: string;
          iteration: number;
          board_index: number;
          board_label: string | null;
          material_id: string | null;
          espesor_mm: number | null;
          largo_placa_mm: number;
          ancho_placa_mm: number;
          area_util_mm2: number;
          area_usada_mm2: number;
          area_desperdicio_mm2: number;
          aprovechamiento_pct: number;
          costo_placa_snapshot: number;
          kerf_mm: number;
          margen_perimetral_mm: number;
          placements_json: Json;
          offcuts_json: Json;
          svg_layout: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          profile_id: string;
          cut_job_id: string;
          iteration: number;
          board_index: number;
          board_label?: string | null;
          material_id?: string | null;
          espesor_mm?: number | null;
          largo_placa_mm: number;
          ancho_placa_mm: number;
          area_util_mm2?: number;
          area_usada_mm2?: number;
          area_desperdicio_mm2?: number;
          aprovechamiento_pct?: number;
          costo_placa_snapshot?: number;
          kerf_mm?: number;
          margen_perimetral_mm?: number;
          placements_json?: Json;
          offcuts_json?: Json;
          svg_layout?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["cut_job_layouts"]["Insert"]>;
      };
      purchases: {
        Row: {
          id: string;
          profile_id: string | null;
          source_type: string;
          source_id: string | null;
          supplier_id: string | null;
          fecha_emision: string;
          fecha_entrega_estimada: string | null;
          status: string;
          moneda: string;
          subtotal_snapshot: number;
          impuestos_snapshot: number;
          total_snapshot: number;
          notas: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
          deleted_at: string | null;
          deleted_by: string | null;
        };
        Insert: {
          id?: string;
          profile_id?: string | null;
          source_type?: string;
          source_id?: string | null;
          supplier_id?: string | null;
          fecha_emision?: string;
          fecha_entrega_estimada?: string | null;
          status?: string;
          moneda?: string;
          subtotal_snapshot?: number;
          impuestos_snapshot?: number;
          total_snapshot?: number;
          notas?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_at?: string | null;
          deleted_by?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["purchases"]["Insert"]>;
      };
      purchase_items: {
        Row: {
          id: string;
          profile_id: string | null;
          purchase_id: string;
          material_id: string | null;
          supplier_id: string | null;
          descripcion_snapshot: string | null;
          cantidad: number;
          unidad_snapshot: string | null;
          costo_unitario_snapshot: number;
          subtotal_snapshot: number;
          cantidad_recibida: number;
          estado: string;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
          deleted_at: string | null;
          deleted_by: string | null;
        };
        Insert: {
          id?: string;
          profile_id?: string | null;
          purchase_id: string;
          material_id?: string | null;
          supplier_id?: string | null;
          descripcion_snapshot?: string | null;
          cantidad?: number;
          unidad_snapshot?: string | null;
          costo_unitario_snapshot?: number;
          subtotal_snapshot?: number;
          cantidad_recibida?: number;
          estado?: string;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_at?: string | null;
          deleted_by?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["purchase_items"]["Insert"]>;
      };
      budgets: {
        Row: {
          id: string;
          profile_id: string | null;
          client_id: string | null;
          custom_project_id: string | null;
          ecommerce_product_id: string | null;
          budget_number: string | null;
          fecha_emision: string;
          fecha_validez: string | null;
          forma_pago: string | null;
          estado: string;
          moneda: string;
          subtotal_snapshot: number;
          descuento_snapshot: number;
          impuestos_snapshot: number;
          total_snapshot: number;
          sena_snapshot: number;
          saldo_snapshot: number;
          costs_snapshot: Json;
          pricing_snapshot: Json;
          terms_snapshot: Json;
          locked_at: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
          deleted_at: string | null;
          deleted_by: string | null;
        };
        Insert: {
          id?: string;
          profile_id?: string | null;
          client_id?: string | null;
          custom_project_id?: string | null;
          ecommerce_product_id?: string | null;
          budget_number?: string | null;
          fecha_emision?: string;
          fecha_validez?: string | null;
          forma_pago?: string | null;
          estado?: string;
          moneda?: string;
          subtotal_snapshot?: number;
          descuento_snapshot?: number;
          impuestos_snapshot?: number;
          total_snapshot?: number;
          sena_snapshot?: number;
          saldo_snapshot?: number;
          costs_snapshot?: Json;
          pricing_snapshot?: Json;
          terms_snapshot?: Json;
          locked_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_at?: string | null;
          deleted_by?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["budgets"]["Insert"]>;
      };
      budget_items: {
        Row: {
          id: string;
          profile_id: string;
          budget_id: string;
          line_order: number;
          concepto: string;
          descripcion: string;
          cantidad: number;
          precio_unitario_snapshot: number;
          descuento_pct_snapshot: number;
          impuestos_pct_snapshot: number;
          subtotal_snapshot: number;
          total_snapshot: number;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          profile_id: string;
          budget_id: string;
          line_order?: number;
          concepto: string;
          descripcion: string;
          cantidad?: number;
          precio_unitario_snapshot?: number;
          descuento_pct_snapshot?: number;
          impuestos_pct_snapshot?: number;
          subtotal_snapshot?: number;
          total_snapshot?: number;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["budget_items"]["Insert"]>;
      };
      jobs_board: {
        Row: {
          id: string;
          profile_id: string | null;
          custom_project_id: string | null;
          budget_id: string | null;
          client_id: string | null;
          titulo: string | null;
          estado: JobStatus | string;
          monto_snapshot: number;
          sena_snapshot: number;
          saldo_snapshot: number;
          fecha_prometida: string | null;
          fecha_inicio: string | null;
          fecha_entrega: string | null;
          avance_pct: number;
          prioridad: number;
          notas: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
          deleted_at: string | null;
          deleted_by: string | null;
        };
        Insert: {
          id?: string;
          profile_id?: string | null;
          custom_project_id?: string | null;
          budget_id?: string | null;
          client_id?: string | null;
          titulo?: string | null;
          estado?: JobStatus | string;
          monto_snapshot?: number;
          sena_snapshot?: number;
          saldo_snapshot?: number;
          fecha_prometida?: string | null;
          fecha_inicio?: string | null;
          fecha_entrega?: string | null;
          avance_pct?: number;
          prioridad?: number;
          notas?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_at?: string | null;
          deleted_by?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["jobs_board"]["Insert"]>;
      };
      attachments: {
        Row: {
          id: string;
          profile_id: string;
          entity_type: string;
          entity_id: string;
          bucket: string;
          file_path: string;
          file_name: string;
          mime_type: string | null;
          size_bytes: number | null;
          checksum_sha256: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
          deleted_at: string | null;
          deleted_by: string | null;
        };
        Insert: {
          id?: string;
          profile_id: string;
          entity_type: string;
          entity_id: string;
          bucket?: string;
          file_path: string;
          file_name: string;
          mime_type?: string | null;
          size_bytes?: number | null;
          checksum_sha256?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_at?: string | null;
          deleted_by?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["attachments"]["Insert"]>;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}

export type PublicSchema = Database["public"];
export type PublicTableName = keyof PublicSchema["Tables"];
export type TableRow<T extends PublicTableName> = PublicSchema["Tables"][T]["Row"];
export type TableInsert<T extends PublicTableName> = PublicSchema["Tables"][T]["Insert"];
export type TableUpdate<T extends PublicTableName> = PublicSchema["Tables"][T]["Update"];

